### ISSUE TITLE
Suggestion -- Update Theme

### ISSUE THREAD

**Issue by Bayside308** [rymate1234/JPanel#12]
Hello!

I was wondering if you would consider changing the theme to a more neutral bootstrap theme, or adding the ability for us to use custom CSS (if you haven't already).

Thanks :)

**Comment by MuhsinunCool** [comment]
I too, would like to be able to have custom themes! Maybe even a theme selector!

**Comment by rymate1234** [comment]
I definitely want to make it easier to customize the look of JPanel - I'm looking into making a custom theme using SASS, so if you want to change some of the colours you can just edit some variables in a vars.scss file.

**Comment by rymate1234** [comment]
As of commit 375914c711ca013ece080ff27a3bef5a6612e8d5, the css of the panel can now be customised by editing either _vars.scss or custom.scss in the JPanel-public folder.

I'll be transitioning the rest of the panel to use the new CSS soon.
