### ISSUE TITLE
[Suggestion] Scroll Bar

### ISSUE THREAD

**Issue by MuhsinunCool** [rymate1234/JPanel#14]
Title says it all. Can u please add a scroll bar to the console? That shudn't be too hard right? Thanks!

**Comment by rymate1234** [comment]
The scroll bar for the console is something that is hidden by css as I thought it made the UI look cleaner. I can probably make this an option in the vars.scss proposed in #12

**Comment by MuhsinunCool** [comment]
Maybe a Settings Page or something? Where I can set different things enabled and disabled. Maybe even have it show the JPanel users and allow one of the admins to change the groups and permissions of lower groups on the fly?
