### ISSUE TITLE
500 Internal Error On Login

### ISSUE THREAD

**Issue by nprail** [rymate1234/JPanel#37]
I just downloaded the source code of JPanel and built it. When I tried to login, it caused a 500 Internal Error which wouldn't go away without clearing my cookies. No errors appeared in the log even when debug mode was on. I'm running Spigot 1.11.2.

**Comment by Speentie8081** [comment]
#36 
This should help you

**Comment by nprail** [comment]
@Speentie8081 I am building the jar. Although, I was using `gradlew assemble` instead of `gradlew build && gradlew`. I figured out the problem. It was some changes I made.
