### ISSUE TITLE
[Bug] Plugin fails to start

### ISSUE THREAD

**Issue by MuhsinunCool** [rymate1234/JPanel#39]
Website never shows up. Simple as that. Using the latest dev build.

**Comment by Speentie8081** [comment]
Works fine for me, make sure you compiled the plugin correctly.

**Comment by MuhsinunCool** [comment]
I didn't compile anything; I just used the latest dev build from Jenkins.

**Comment by Speentie8081** [comment]
There is no Jenkins for this project? Can you link me?

**Comment by MuhsinunCool** [comment]
Well then... it's gone... I swear there used to be one on the code tab in the README.md... Could you explain to me how I would go about compiling this? Do I have to use Eclipse? Or is there an easier way?

**Comment by rymate1234** [comment]
No IDEs needed, just the Java 8 SDK.

Just download the source, open a terminal in the directory with gradlew.bat, and run:

    gradlew.bat debugJar

Assuming no build errors, you'll find a development version of JPanel in `build/libs/`

**Comment by MuhsinunC** [comment]
Thanks! :D

**Comment by MuhsinunC** [comment]
It works! :D
