### ISSUE TITLE
RAM Usage bar

### ISSUE THREAD

**Issue by H0bbitBaron** [rymate1234/JPanel#48]
Hi, @rymate1234, how do i interpret 'RAM Usage' bar? I use -Xmx1800M and Jpanel shows smthng like 'RAM: 516MB / **1016**MB', but I expected smthng like this 'RAM: 516MB / **1800**MB'. Thank you in advance!

**Comment by ghost** [comment]
Interpret it as it is, 1016mb is actually the total of what the server has been allocated in ram, and 516mb is the total of what the server has used of the allocated amount of ram, Java virtual machines don't use all the memory that has been specified for it. For example,
![image](https://user-images.githubusercontent.com/12576827/37257292-932f52ec-2535-11e8-8e06-c27a10d1e10c.png)
 this is what my server looks like when allocated 8192mb of ram and viewed through JPanel. It is accurate and there is no issue with the project, it is just how java works, accept it for how it is. Part of the reason it might be so low as compared to 1800mb could be that roughly 784mb is currently being used for the java virtual machine to run, or system ram usage at server execution + 1800mb is > maximum system ram, then it will lower the allocated ram usage.
